version: "3.7"

services:

  tensorflow:
    container_name: hackathon-dashboard-copia2
    build:
      context: ./dashboard
    ports:
      - "5000:5000"
    networks:
      - market_net
    environment:
      OPENAI_API_KEY: "sk-proj-kB4O089HZCL2vsrMXRFET3BlbkFJz17zAt2GQ56uG9Qzj2A4"
    volumes:
      - ./dashboard:/app 

networks:
  market_net:
    driver: bridge